version: '3.9'

services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pss1Klps
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dotsafedb1
    ports:
      - '3306:3306'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8010:80
    environment:
      PMA_HOST: mariadb
    networks:
      - dev

networks:
  dev:
